### ISSUE TITLE
Clarify handling of existing connections to unhealthy targets

### ISSUE THREAD

**Issue by adanilinel1** [awsdocs/elb-network-load-balancers-user-guide#12]
Could you please clarify what happens to the existing non-idle connections once a target becomes unhealthy (due to http health check failure, etc)?
Do they stay open until closed by one of the parties?
"Deregistration delay" section implies that the connections are closed:

> To ensure that existing connections are closed, you can ensure that the instance is unhealthy before you deregister it, or you can periodically close client connections.

https://github.com/awsdocs/elb-network-load-balancers-user-guide/blob/8c7ea44e1c34d8938050c5eeb71e63fb861d61a7/doc_source/load-balancer-target-groups.md#deregistration-delay

**Comment by julieso** [comment]
Hello. Connections to unhealthy targets are terminated.
