### ISSUE TITLE
S3 Access logs for NLB only support encryption type as "SSE-S3"

### ISSUE THREAD

**Issue by naman-balodiya** [awsdocs/elb-network-load-balancers-user-guide#20]
Document for NLB S3 access log does not say clearly that it only support SSE-S3, no other encryption option (like KMS) is supported.

Rather than:
Enable server-side encryption with Amazon S3-Managed Encryption Keys (SSE-S3)
which is on `https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html#:~:text=that%20you%20specify.-,Enable%20server-side%20encryption%20with%20Amazon%20S3-Managed%20Encryption%20Keys%20(SSE-S3),-.`

We can say:
Amazon S3-Managed Encryption Keys (SSE-S3) is required. No other encryption options are supported

**Comment by julieso** [comment]
Apologies for the delayed response. The current documentation shows that SSE-KMS is supported.
