### ISSUE TITLE
Proxy Protocol table isn't clear

### ISSUE THREAD

**Issue by wolruf** [awsdocs/elb-network-load-balancers-user-guide#4]
Hello,
The table is confusing:
- e.g using bytes vs octets
PP2_SUBTYPE_AWS_VPCE_ID (0x01)- using description such as "PP2_TYPE_AWS (0xEA)" and "" for both Type and Value.
- use of "length of value" and "value length" sentences in the same table

**Comment by julieso** [comment]
Hi. Yes, most times a byte is 8 bits, just like an octet. I was asked to document these as octets. Would it help if I changed the column head from "Description" to "Contents" and changed "The length of value" to "The length of Value" and "variable (value length minus 1)" to "Length minus 1"?
